name = str(input("Enter your name : "))
age= int(input("Enter your age : "))
roll_no= int(input(" Enter your roll no : "))
email_id= str(input("Enter your email id : "))
mobile_no= int(input("Enter your mobile no : "))
address= str(input("Enter your address : "))

print("Name : ",name)
print("Age : ",age)
print("roll no : ",roll_no)
print("email id : ",email_id)
print("Mobile no :",mobile_no)
print("Address : ",address)